version: 2.1

jobs:
  build:
    docker:
      - image: cimg/ruby:3.2.2
    steps:
      - checkout

      - run:
          name: Build gem
          command: gem build mail_interceptor

      - run: bundle install

      - run:
          name: Run tests
          command: bundle exec rake test
